### ISSUE TITLE
Change "Do not hoard masks" to "Do not hoard surgical masks"

### ISSUE THREAD

**Issue by paul-hammant** [flattenthecurve/guide#198]
If you want to craveat that, then say don't hoard N95, FFP1, FFP2 or FFP3 masks.

**Cloth masks should be encouraged for civilians.** Ref https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2440799 as they do not deplete the masks that medical professionals use. That notwithstanding https://www.sacbee.com/news/coronavirus/article241330531.html and https://www.deaconess.com/How-to-make-a-Face-Mask

**Comment by jaysonvirissimo** [comment]
Alternatively, [remove the whole section](https://github.com/flattenthecurve/guide/pull/131), since it is too vague and contains poor arguments.

**Comment by steesdale** [comment]
Perhaps we can flip this to the proactive/positive.  Specifically things like, 
- If you are sick, wear a mask to prevent getting others sick
- If you are high risk due to health status or profession/caretaker status.  Consider wearing an N95 style mask but be sure to get help to practice and train on how to use them.  
- etc...  

@jaysonvirissimo  and @paul-hammant would you all be willing to draft something more concise and well-cited with primary sources?

**Comment by jaysonvirissimo** [comment]
I can draft something, but it won’t be until tomorrow night. Don’t wait for me if you can get to it before then @paul-hammant.

**Comment by paul-hammant** [comment]
US health services group Deaconess Health Systems shares a mask design as part of their appeal for **cloth masks** (March 20):

PDF: https://www.deaconess.com/How-to-make-a-Face-Mask/Documents-Mask/Mask-Information Video: https://youtu.be/9tBg0Os5FWQ

US health services group Providence shares a **cloth mask** design video (March 21) - part of their "100 million mask" initiative:

Video: https://vimeo.com/399324367/13cd93f150

**Comment by paul-hammant** [comment]
I stand by what I said - "do not hard surgical masks" https://github.com/flattenthecurve/guide/issues/203 is for pro-mask content.

**Comment by paul-hammant** [comment]
As reqeuested https://github.com/flattenthecurve/guide/pull/204

**Comment by paul-hammant** [comment]
And as @jaysonvirissimo said, much of that section just needs to go. Nobody on earth can remain associated with the "masks don't work messaging".

**Comment by mverzilli** [comment]
Just merged https://github.com/flattenthecurve/guide/pull/131 that removed the whole section. @paul-hammant I did see your PRs but since the section was going away I didn't want to act on those to avoid inconsistencies. Please feel free to open a new one with a new do/dont reflecting this conversation.

**Comment by paul-hammant** [comment]
Section is still on the hosted site. Is there a delay on publication?  Netlift can use a GitHub WebHook to trigger build/deploys.

**Comment by jaysonvirissimo** [comment]
I think we can close this now that the offending section has been removed (although the idea of specifying the _kind_ of mask we mean in various places would generally improve things).

**Comment by paul-hammant** [comment]
agree
