### ISSUE TITLE
Add "wear / build a mask"

### ISSUE THREAD

**Issue by josselex** [flattenthecurve/guide#34]
In east asian countries where they are quite successfully fighting the desease everybody is obliged to wear a mask.

There are studies that even self-built masks protect in both ways:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2440799/

I think it is a good idea to start to wear masks, especially to protect others. It also raises awareness and keeps you from touching your mouth/nose.

**Comment by danimiba** [comment]
I would highly recommend asking for more advice and evidence. According to de CDC, wearing a mask is not the way to go against this: https://www.cdc.gov/coronavirus/2019-ncov/hcp/respirator-use-faq.html

It actually says that we shouldn't buy N95 as to let them be available to health facilities.

**Comment by steesdale** [comment]
Masks work to prevent you from getting others sick. 

They don’t work for average people for keeping from getting sick.  This is because people don’t understand or train on how to size, fit, take on/off, handle the mask correctly.  

Largely it has been seen to give people a false sense of security...

**Comment by josselex** [comment]
> Masks work to prevent you from getting others sick.
> They don’t work for average people for keeping from getting sick. This is because people don’t understand or train on how to size, fit, take on/off, handle the mask correctly.

Yes. That's why you should wear them! Think of society, wear a mask.
 
> Largely it has been seen to give people a false sense of security...

Do you have any source for this? And again: Why do countries who sucessfully fight Corona recommend different?
And actually I think people running around with masks earlier would have increased awareness in a lot of people.

**Comment by mattbell** [comment]
I did a lot of research into masks a few days ago and concluded that they should be worn by members of the public if they have them, even if the masks are improvised.

----
Wear a mask in public.  
 
Wearing a mask, even an improvised one, is better than no mask.  
 
A P100 respirator is better than a N95 mask, which is better than a surgical mask, which is better than a scarf or pillowcase, which is better than nothing.  Don’t despair if you don’t have the best mask.  Make do with what you have.  Try to get it to fit as well as possible.  
 
In addition to some degree of protection against inhaling droplets with virus in them (or exhaling onto others if you’re sick), masks will prevent you from touching the mucous membranes of your face with dirty hands when you’re out in public.
 
Numerous studies show that masks can cut down on influenza transmission.  [0]  Nearly every Asian public health ministry recommends that people wear masks in public, especially during the winter flu season.  Hong Kong, Singapore, South Korea, and Taiwan all recommend wearing masks, and all of these countries have been effective in slowing the spread of COVID-19 within their borders.  
 
Since mask supply is limited, there are questions about mask reuse.  There are conflicting reports about whether it is safe to sterilize and reuse masks. [1] [4]  Almost everyone recommends discarding masks once used in a high-risk setting (eg a hospital, or contact with a person with COVID-19).  However, reuse after low-risk use may be possible.  Some sources claim that improvised fabric or surgical masks can be sterilized in boiling water and then dried, disinfected with UVC light, or left out in the sunlight for several days. [0] [1]   N95 masks need to stay dry.  An old study from SARS-CoV suggests that temperatures of 60C / 140F for 30 minutes will destroy a different coronavirus. [2] There is no analogous study for this coronavirus yet, but it’s likely its temperature tolerance is similar.  N95 masks appear to only mildly be damaged by this level of heat. [3]  Thus, it’s possible you could “bake” your used N95 masks at low heat in the oven (eg 180F) to sterilize them without damaging them.  I’ve tested this on the 3M brand N95 masks we have and it appeared to work.    
 
Thinking systemically, it’s true that healthcare workers have the greatest need for masks as they have the greatest exposure.  However, that doesn’t mean you shouldn’t take whatever you already have and make use of it.  Contrary to what the CDC is saying, masks do help prevent the spread of influenza, and there’s ample research to support it.  
 
I believe the CDC is trying to cover for the fact that they did not adequately stockpile masks for a pandemic, and now they don’t have enough for healthcare workers.  They could have said “Hey, we messed up big time, and we need you all to make a small personal sacrifice so that the people who are putting their lives on the line are adequately protected.  We’re going to make sure this never happens again.”  But instead they’re saying “The Centers for Disease Control and prevention does not recommend that well people wear a face mask to protect themselves from respiratory illnesses, including COVID-19”.    
 
This goes without saying, but wearing a mask alone won’t protect you.  You should be regularly washing/sanitizing your hands and avoiding crowds if at all possible.  
 
------------
 
Sources:
 
The case for masks
[0] https://www.inkstonenews.com/health/coronavirus-health-researchers-urge-global-authorities-consider-broadening-use-face-masks/article/3074453
 
Washing surgical masks:
[1] https://focustaiwan.tw/society/202002020012
 
Heat for inactivation of the original SARS coronavirus:
[2] https://www.ncbi.nlm.nih.gov/pubmed/15118911
 
Mask safety during sanitization
[3] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2781738/
 
Claims of mask steaming as ineffective:
[4] https://factcheck.afp.com/novel-coronavirus-health-experts-warn-against-steaming-face-masks-reuse-after-misinformation-chinese
 
Homemade masks: https://www.researchgate.net/publication/258525804_Testing_the_Efficacy_of_Homemade_Masks_Would_They_Protect_in_an_Influenza_Pandemic
https://academic.oup.com/annweh/article/54/7/789/202744
 
Surgical masks and N95 masks:
https://www.ncbi.nlm.nih.gov/pubmed/23498357
https://www.ncbi.nlm.nih.gov/pubmed/20095070
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306645/  (interesting experimental setup)
 
Home wearing of masks to prevent family members infecting one another:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2662657/
 
Good Reddit discussion:
https://www.reddit.com/r/Coronavirus/comments/fgorv3/no_need_to_wear_a_mask_experts_urge_health/fk5xppo/

**Comment by bajeluk** [comment]
Thanks, @mattbell, I 100% agree with you.

Btw. almost everyone has started to wear (mostly improvised) masks in central Europe during the last 3 days (2020-03-16 to 2020-03-18), it has become even mandatory in public areas in the Czech Republic.

**Comment by mattbell** [comment]
BTW, I'm new here.  Should I go ahead and take the initiative to write something up that's ready for insertion into the site?

**Comment by nicolevasilevsky** [comment]
Seems like this is somewhat controversial - I am in favor of adding the pros and cons to the site, so people can make their own informed decisions

**Comment by steesdale** [comment]
This piece was just published in lancet ->. https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30520-1/fulltext?dgcid=raven_jbs_etoc_email 

Does a nice job of laying out pro' sand cons and challenges.

**Comment by paul-hammant** [comment]
I've been maintaining https://cv-masks.github.io/ for most of March. I've six studies that are pro-mask for same-viron-size Influenza self-protection :)

**Comment by jmcmurry** [comment]
Washing and drying the washable masks makes plenty of sense, but we need to address the related issue of re-using masks that are not washable. SARS-CoV2 viability on plastic/metal is only 3 days but fomite transmission may be implicated (no hard evidence for this, but we should be erring on the side of safety).

![image](https://user-images.githubusercontent.com/3658863/77233557-89716380-6b65-11ea-86e1-933f3a5fb486.png)

![image](https://user-images.githubusercontent.com/3658863/77233536-56c76b00-6b65-11ea-9e7c-860c3ca78cfe.png)

Appl Environ Microbiol. 2007 Mar; 73(6): 1687–1696.
Published online 2007 Jan 12. doi: 10.1128/AEM.02051-06
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1828811/

**Comment by jmcmurry** [comment]
By that I mean we should probably, in the absence of hard data either way, recommend people not reuse masks unless they have sat untouched for 10 days. @steesdale ?

**Comment by jmcmurry** [comment]
There are many complex variables that influence virus survival on fomites, viral transfer from fomites, and viral infection of the host (7, 10, 24, 66). As a result, direct experimental evidence of viral transmission via fomite has been very difficult to generate due to a variety of uncontrollable variables and the unpredictability of human infection (7, 66). An example of the difficulty in producing illness in the host after exposure was indicated in the Gwaltney study using rhinovirus. Over a 10-year period, Gwaltney intranasally challenged 343 adults without rhinovirus antibodies and infected 95% of the participants (28). However, only 30% of the individuals who became infected displayed disease symptoms (28). Generally, the majority of laboratory and clinical evidence is considered indirect; however, fomite transmission data are supported by both epidemiological studies and intervention studies.

Epidemiological data indicating transmission via fomite are also difficult to evaluate (19). This difficulty stems from problems in distinguishing between different routes of transmission, such as person-to-person transmission or autoinoculation (19). Currently, laboratory studies, epidemiological evidence, and disinfection intervention studies have generated strong indirect and circumstantial evidence that supports the involvement of fomites as a vehicle in respiratory and enteric virus transmission. Studies from a variety of disciplines investigating viruses clearly support the following: (i) most respiratory and enteric viruses can survive on fomites and hands for varying lengths of time; (ii) fomites and hands can become contaminated with viruses from both natural and laboratory sources; (iii) viral transfer from fomites to hands is possible; (iv) hands come in contact with portals of entry for viral infection; and (v) disinfection of fomites and hands interrupts viral transmission (7, 24, 66).

**Comment by jaysonvirissimo** [comment]
While we discuss a "wear/build mask" section, can we at least [remove the recommendation against masks](https://github.com/flattenthecurve/guide/pull/131) in the mean time?

It is currently waiting for `sci-review`.

@anarchodoc had misgivings about recommending masks, but seemed to be okay with removing the existing section, so I'm pinging them here to ensure they are aware of _this_ discussion too.

**Comment by anarchodoc** [comment]
Hi, thanks @jaysonvirissimo for the ping. As you can imagine, I'm now getting busy with other work :/

I have huge misgivings about masks, based on this article in the BMJ and on my broader knowledge about people (I'm a medic and an epidemiologist). 
BMJ abstract: https://www.bmj.com/content/350/bmj.h694 however the article requires login so if you can't get it try looking for the reference in SciHub - currently available at https://sci-hub.tw/ or https://sci-hub.se/

The oft-quoted PLOS One article is interesting but not really relevant to the situation - it looks at people in a very controlled circumstance wearing a mask for 10-15 minutes, and at the beginning and end of 3 hours. In the real world, I do not believe that the results will hold: behaviours will be different. 

Indeed, the BMJ article suggests that the most important thing about wearing a face mask is it modifies behaviour (only the studies where handwashing was also included showed a difference). In the current situation, wearing a mask will not stop viral transmission via inhalation but will limit the amount of time you put your hand to your face and thus potentially reduce transmission in that fashion. 

There is also a desperate shortage of masks worldwide and they should be reserved for health care professionals in settings where there is better evidence that they are likely to make a difference (rather than people just walking around on the street). Hence why I cannot currently condone people wearing them.

**Comment by paul-hammant** [comment]
@anarchodoc do you mean a "shortage of surgical and N95/FFP1/2/3 masks" or do you mean to include cloth masks too when you say "shortage of masks" ?

**Comment by anarchodoc** [comment]
@paul-hammant correct, I did not mean cloth masks or self-made ones.

**Comment by mattbell** [comment]
FWIW I don't think there is still a worldwide shortage of masks.  As the crisis ramps down in China, they now have crazy big production capacity (China is making 110 million+ masks a day).  Several of my friends are involved in very large volume purchasing of masks for distribution to hospitals in the US.

**Comment by anarchodoc** [comment]
@mattbell  There's a definite shortage where I am (Europe). It will also take a  while for those masks to get places. and 110+ million a day isn't that many - there are how many people on the planet??

 And I bet people in Africa wouldn't agree with you either.

**Comment by jaysonvirissimo** [comment]
@anarchodoc, @mattbell: I think we can agree that our recommendation should be conditional on facts on the ground for the various regions. For example, if there are shortages of PPE at local hospitals you should donate your N95s and wear/make cloth masks, but if there isn't you should wear them yourself, etc...

**Comment by paul-hammant** [comment]
So we all agree "make/buy/use cloth masks good" ?  Can we work that into the site, please?

**Comment by mattbell** [comment]
I spent a lot of time researching masks over the last couple of days.  I put this together into a post:  https://medium.com/@llebttam_45762/masks-work-wear-them-b450ac9f3b7d

I'd be happy to turn any portion of this into a post for flattenthecurve if you'd like.  Just let me know the scope and length and I can make it happen.

**Comment by rousik** [comment]
CDC is now reversing its recommendations, suggests wearing masks in public and various states are rolling out recommendations for home-made masks in public (e.g. Colorado). I think we should follow suit and update our website accordingly.

**Comment by jaysonvirissimo** [comment]
@rousik: we already have a ["Wear a facemask when in public"](https://www.flattenthecurve.com/act-and-prepare/#wear-a-facemask-when-in-public) section.

@josselex we can close this issue now. 👍
