### ISSUE TITLE
Is it "flatten the curve" or "crush the curve"?

### ISSUE THREAD

**Issue by SokolskyNikita** [flattenthecurve/guide#372]
As discussed in [a related Issue](https://github.com/flattenthecurve/guide/issues/89), there now seems to be a disconnect in society over what "flatten the curve" actually means.

 1. Original meaning: "Let's shelter in place so that our hospitals are not overrun, while we stock up on PPE, medicine, hospital beds, etc, etc. Everyone will be infected anyway, but we should spread the disease out to avoid collapsing the medical system".
 2. Novel meaning: "Let's shelter in place until we can either eliminate the virus altogether (New Zealand or Iceland style) or until we can all get a vaccine. No deaths from COVID-19 are acceptable, even if our hospitals are wide open".

Which of the two strategies is currently being supported by the website? Could the front page clarify this somehow? Right now there's a lot of confusion in society over what "flatten the curve" actually means, so it would be nice to firmly assert one position or the other.

**Comment by jaysonvirissimo** [comment]
More clarity would def be welcomed by me: if we are actually in favor of (2), it should be noted that although crushthecurve.com has been registered since 2014, it is actually already being used for a COVID-19 project.

**Comment by jmcmurry** [comment]
When I first published this guide it was because I couldn't find the content elsewhere. Everything was either super anemic, over-confident, overly technical, or overly pedantic. The average citizen at least in the USA was therefore not well prepared.

There are practical limitations in terms of how quickly the content can shift and there are also ethical considerations and local needs that may differ across national or even state lines. I think that emphasizing the how to protect ones self and each other should be the focus and some of the originally gentler guidance about distancing quickly was superseded by stay-home orders. As restrictions start to lift, albeit unevenly, that gentler guidance will be more relevant than ever. The policy makers will have to be guided by local factors but how individuals take responsibility for themselves and their communities will not go away.
